### ISSUE TITLE
Does it use multithreading ?

### ISSUE THREAD

**Issue by julienlau** [hobuinc/hexer#25]
It seems that the algo is parallelizable: using a map/reduce approach where each chunk of data would bring its contribution to global accounting ? 

I know PDAL is not, but PDAL is really slow to compute boundary on large LAZ.
Any change that this version of boundary computation would be quicker ?

Thanks and regards

**Comment by abellgithub** [comment]
This isn't PDAL. Perhaps you should open a ticket on the PDAL project.

**Comment by julienlau** [comment]
I know it is not PADL, I am just interested by the hexer boundary !

**Comment by abellgithub** [comment]
There is no threading in this code. The likely bottleneck is reading and decoding LAZ -- if you want this to run faster, that's probably the place to focus, but I'm sure there are other performance improvements that can be made.
